[package]
name = "utils"
version = "0.1.1"
edition = "2021"

[lib]
name = "utils"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
bimap="0.6.2"
either = "1.6.1"
indexmap = "1.8.0"